import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Octokit } from "octokit";
import React, { useEffect } from "react";

const inter = Inter({ subsets: ['latin'] })

const octokit = new Octokit({
});

const queryString = window.location.search;

const urlParams = new URLSearchParams(queryString);

const client_secret = 'ab3375dda2387cf2e6c666f759fdf65bd982b724';
const client_id = '823088350817b5fcb472';
const code = urlParams.get('code');


function fetch() {
    octokit.request("POST https://github.com/login/oauth/access_token", {
        client_id : client_id,
        client_secret : client_secret,
        code : code,
        redirect_uri : 'http://localhost:3000/'
    });
}
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <a href="https://github.com/login/oauth/authorize?client_id=823088350817b5fcb472&redirect_uri=http://localhost:3000/">
              <button>
                  Login with GitHub
              </button>
              <button onClick={fetch}>test</button>
          </a>
      </main>
    </>
  )
}
